export const REQUEST_LOGIN = 'REQUEST_LOGIN'
export const REQUEST_LOGIN_SUCCESS = 'REQUEST_LOGIN_SUCCESS'
export const REQUEST_LOGIN_FAILURE = 'REQUEST_LOGIN_FAILURE'

export const REQUEST_LOGOUT = 'REQUEST_LOGOUT'

export const REQUEST_FORGOT_PWD = 'REQUEST_FORGOT_PWD'
export const REQUEST_FORGOT_PWD_SUCCESS = 'REQUEST_FORGOT_PWD_SUCCESS'
export const REQUEST_FORGOT_PWD_FAILURE = 'REQUEST_FORGOT_PWD_FAILURE'

export const REQUEST_EMAIL_VERIFY = 'REQUEST_EMAIL_VERIFY'
export const REQUEST_EMAIL_VERIFY_SUCCESS = 'REQUEST_EMAIL_VERIFY_SUCCESS'
export const REQUEST_EMAIL_VERIFY_FAILURE = 'REQUEST_EMAIL_VERIFY_FAILURE'

export const REQUEST_RESET_PWD = 'REQUEST_RESET_PWD'
export const REQUEST_RESET_PWD_SUCCESS = 'REQUEST_RESET_PWD_SUCCESS'
export const REQUEST_RESET_PWD_FAILURE = 'REQUEST_RESET_PWD_FAILURE'

export const REQUEST_CHANGE_PWD = 'REQUEST_CHANGE_PWD'
export const REQUEST_CHANGE_PWD_SUCCESS = 'REQUEST_CHANGE_PWD_SUCCESS'
export const REQUEST_CHANGE_PWD_FAILURE = 'REQUEST_CHANGE_PWD_FAILURE'

export const FETCH_ASSETS = 'FETCH_ASSETS'
export const FETCH_ASSETS_SUCCESS = 'FETCH_ASSETS_SUCCESS'
export const FETCH_ASSETS_FAILURE = 'FETCH_ASSETS_FAILURE'

export const CREATE_ASSET = 'CREATE_ASSET'
export const CREATE_ASSET_SUCCESS = 'CREATE_ASSET_SUCCESS'
export const CREATE_ASSET_FAILURE = 'CREATE_ASSET_FAILURE'

export const DELETE_ASSET = 'DELETE_ASSET'
export const DELETE_ASSET_SUCCESS = 'DELETE_ASSET_SUCCESS'
export const DELETE_ASSET_FAILURE = 'DELETE_ASSET_FAILURE'

export const FETCH_USERS = 'FETCH_USERS'
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS'
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE'

export const FETCH_USER = 'FETCH_USER'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE'

export const CREATE_USER = 'CREATE_USER'
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS'
export const CREATE_USER_FAILURE = 'CREATE_USER_FAILURE'

export const UPDATE_USER = 'UPDATE_USER'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE'

export const ACTIVATE_USER = 'ACTIVATE_USER'
export const ACTIVATE_USER_SUCCESS = 'ACTIVATE_USER_SUCCESS'
export const ACTIVATE_USER_FAILURE = 'ACTIVATE_USER_FAILURE'

export const DEACTIVATE_USER = 'DEACTIVATE_USER'
export const DEACTIVATE_USER_SUCCESS = 'DEACTIVATE_USER_SUCCESS'
export const DEACTIVATE_USER_FAILURE = 'DEACTIVATE_USER_FAILURE'

export const DELETE_USER = 'DELETE_USER'
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS'
export const DELETE_USER_FAILURE = 'DELETE_USER_FAILURE'

export const FETCH_ACTIONS = 'FETCH_ACTIONS'
export const FETCH_ACTIONS_SUCCESS = 'FETCH_ACTIONS_SUCCESS'
export const FETCH_ACTIONS_FAILURE = 'FETCH_ACTIONS_FAILURE'

export const FETCH_ROLE = 'FETCH_ROLE'
export const FETCH_ROLE_SUCCESS = 'FETCH_ROLE_SUCCESS'
export const FETCH_ROLE_FAILURE = 'FETCH_ROLE_FAILURE'

export const UPDATE_ROLE = 'UPDATE_ROLE'
export const UPDATE_ROLE_SUCCESS = 'UPDATE_ROLE_SUCCESS'
export const UPDATE_ROLE_FAILURE = 'UPDATE_ROLE_FAILURE'

export const FETCH_CUSTOMERS = 'FETCH_CUSTOMERS'
export const FETCH_CUSTOMERS_SUCCESS = 'FETCH_CUSTOMERS_SUCCESS'
export const FETCH_CUSTOMERS_FAILURE = 'FETCH_CUSTOMERS_FAILURE'

export const FETCH_CUSTOMER = 'FETCH_CUSTOMER'
export const FETCH_CUSTOMER_SUCCESS = 'FETCH_CUSTOMER_SUCCESS'
export const FETCH_CUSTOMER_FAILURE = 'FETCH_CUSTOMER_FAILURE'

export const CREATE_CUSTOMER = 'CREATE_CUSTOMER'
export const CREATE_CUSTOMER_SUCCESS = 'CREATE_CUSTOMER_SUCCESS'
export const CREATE_CUSTOMER_FAILURE = 'CREATE_CUSTOMER_FAILURE'

export const UPDATE_CUSTOMER = 'UPDATE_CUSTOMER'
export const UPDATE_CUSTOMER_SUCCESS = 'UPDATE_CUSTOMER_SUCCESS'
export const UPDATE_CUSTOMER_FAILURE = 'UPDATE_CUSTOMER_FAILURE'

export const DELETE_CUSTOMER = 'DELETE_CUSTOMER'
export const DELETE_CUSTOMER_SUCCESS = 'DELETE_CUSTOMER_SUCCESS'
export const DELETE_CUSTOMER_FAILURE = 'DELETE_CUSTOMER_FAILURE'

export const FETCH_CERTIFIERS = 'FETCH_CERTIFIERS'
export const FETCH_CERTIFIERS_SUCCESS = 'FETCH_CERTIFIERS_SUCCESS'
export const FETCH_CERTIFIERS_FAILURE = 'FETCH_CERTIFIERS_FAILURE'

export const FETCH_CERTIFIER = 'FETCH_CERTIFIER'
export const FETCH_CERTIFIER_SUCCESS = 'FETCH_CERTIFIER_SUCCESS'
export const FETCH_CERTIFIER_FAILURE = 'FETCH_CERTIFIER_FAILURE'

export const CREATE_CERTIFIER = 'CREATE_CERTIFIER'
export const CREATE_CERTIFIER_SUCCESS = 'CREATE_CERTIFIER_SUCCESS'
export const CREATE_CERTIFIER_FAILURE = 'CREATE_CERTIFIER_FAILURE'

export const UPDATE_CERTIFIER = 'UPDATE_CERTIFIER'
export const UPDATE_CERTIFIER_SUCCESS = 'UPDATE_CERTIFIER_SUCCESS'
export const UPDATE_CERTIFIER_FAILURE = 'UPDATE_CERTIFIER_FAILURE'

export const DELETE_CERTIFIER = 'DELETE_CERTIFIER'
export const DELETE_CERTIFIER_SUCCESS = 'DELETE_CERTIFIER_SUCCESS'
export const DELETE_CERTIFIER_FAILURE = 'DELETE_CERTIFIER_FAILURE'

export const FETCH_PROJECTS = 'FETCH_PROJECTS'
export const FETCH_PROJECTS_SUCCESS = 'FETCH_PROJECTS_SUCCESS'
export const FETCH_PROJECTS_FAILURE = 'FETCH_PROJECTS_FAILURE'

export const FETCH_PROJECT = 'FETCH_PROJECT'
export const FETCH_PROJECT_SUCCESS = 'FETCH_PROJECT_SUCCESS'
export const FETCH_PROJECT_FAILURE = 'FETCH_PROJECT_FAILURE'

export const FETCH_PROJECT_INFO = 'FETCH_PROJECT_INFO'
export const FETCH_PROJECT_INFO_SUCCESS = 'FETCH_PROJECT_INFO_SUCCESS'
export const FETCH_PROJECT_INFO_FAILURE = 'FETCH_PROJECT_INFO_FAILURE'

export const CREATE_PROJECT = 'CREATE_PROJECT'
export const CREATE_PROJECT_SUCCESS = 'CREATE_PROJECT_SUCCESS'
export const CREATE_PROJECT_FAILURE = 'CREATE_PROJECT_FAILURE'

export const UPDATE_PROJECT = 'UPDATE_PROJECT'
export const UPDATE_PROJECT_SUCCESS = 'UPDATE_PROJECT_SUCCESS'
export const UPDATE_PROJECT_FAILURE = 'UPDATE_PROJECT_FAILURE'

export const UPDATE_PROJECT_STATUS = 'UPDATE_PROJECT_STATUS'
export const UPDATE_PROJECT_STATUS_SUCCESS = 'UPDATE_PROJECT_STATUS_SUCCESS'
export const UPDATE_PROJECT_STATUS_FAILURE = 'UPDATE_PROJECT_STATUS_FAILURE'

export const UPDATE_PROJECT_DWELLING_UNIT = 'UPDATE_PROJECT_DWELLING_UNIT'
export const UPDATE_PROJECT_DWELLING_UNIT_SUCCESS = 'UPDATE_PROJECT_DWELLING_UNIT_SUCCESS'
export const UPDATE_PROJECT_DWELLING_UNIT_FAILURE = 'UPDATE_PROJECT_DWELLING_UNIT_FAILURE'

export const UPDATE_PROJECT_CERTIFIER = 'UPDATE_PROJECT_CERTIFIER'
export const UPDATE_PROJECT_CERTIFIER_SUCCESS = 'UPDATE_PROJECT_CERTIFIER_SUCCESS'
export const UPDATE_PROJECT_CERTIFIER_FAILURE = 'UPDATE_PROJECT_CERTIFIER_FAILURE'

export const UPDATE_PROJECT_CUSTOMER = 'UPDATE_PROJECT_CUSTOMER'
export const UPDATE_PROJECT_CUSTOMER_SUCCESS = 'UPDATE_PROJECT_CUSTOMER_SUCCESS'
export const UPDATE_PROJECT_CUSTOMER_FAILURE = 'UPDATE_PROJECT_CUSTOMER_FAILURE'

export const DELETE_PROJECT = 'DELETE_PROJECT'
export const DELETE_PROJECT_SUCCESS = 'DELETE_PROJECT_SUCCESS'
export const DELETE_PROJECT_FAILURE = 'DELETE_PROJECT_FAILURE'

export const FETCH_DEDUCTIONS = 'FETCH_DEDUCTIONS'
export const FETCH_DEDUCTIONS_SUCCESS = 'FETCH_DEDUCTIONS_SUCCESS'
export const FETCH_DEDUCTIONS_FAILURE = 'FETCH_DEDUCTIONS_FAILURE'

export const FETCH_LPDS = 'FETCH_LPDS'
export const FETCH_LPDS_SUCCESS = 'FETCH_LPDS_SUCCESS'
export const FETCH_LPDS_FAILURE = 'FETCH_LPDS_FAILURE'

export const FETCH_DWELLING_UNITS = 'FETCH_DWELLING_UNITS'
export const FETCH_DWELLING_UNITS_SUCCESS = 'FETCH_DWELLING_UNITS_SUCCESS'
export const FETCH_DWELLING_UNITS_FAILURE = 'FETCH_DWELLING_UNITS_FAILURE'

export const FETCH_DWELLING_UNIT = 'FETCH_DWELLING_UNIT'
export const FETCH_DWELLING_UNIT_SUCCESS = 'FETCH_DWELLING_UNIT_SUCCESS'
export const FETCH_DWELLING_UNIT_FAILURE = 'FETCH_DWELLING_UNIT_FAILURE'

export const CREATE_DWELLING_UNIT = 'CREATE_DWELLING_UNIT'
export const CREATE_DWELLING_UNIT_SUCCESS = 'CREATE_DWELLING_UNIT_SUCCESS'
export const CREATE_DWELLING_UNIT_FAILURE = 'CREATE_DWELLING_UNIT_FAILURE'

export const UPDATE_DWELLING_UNIT = 'UPDATE_DWELLING_UNIT'
export const UPDATE_DWELLING_UNIT_SUCCESS = 'UPDATE_DWELLING_UNIT_SUCCESS'
export const UPDATE_DWELLING_UNIT_FAILURE = 'UPDATE_DWELLING_UNIT_FAILURE'

export const DELETE_DWELLING_UNIT = 'DELETE_DWELLING_UNIT'
export const DELETE_DWELLING_UNIT_SUCCESS = 'DELETE_DWELLING_UNIT_SUCCESS'
export const DELETE_DWELLING_UNIT_FAILURE = 'DELETE_DWELLING_UNIT_FAILURE'

export const CREATE_PROJECT_PHOTO = 'CREATE_PROJECT_PHOTO'
export const CREATE_PROJECT_PHOTO_SUCCESS = 'CREATE_PROJECT_PHOTO_SUCCESS'
export const CREATE_PROJECT_PHOTO_FAILURE = 'CREATE_PROJECT_PHOTO_FAILURE'

export const UPDATE_PROJECT_PHOTO = 'UPDATE_PROJECT_PHOTO'
export const UPDATE_PROJECT_PHOTO_SUCCESS = 'UPDATE_PROJECT_PHOTO_SUCCESS'
export const UPDATE_PROJECT_PHOTO_FAILURE = 'UPDATE_PROJECT_PHOTO_FAILURE'

export const DELETE_PROJECT_PHOTO = 'DELETE_PROJECT_PHOTO'
export const DELETE_PROJECT_PHOTO_SUCCESS = 'DELETE_PROJECT_PHOTO_SUCCESS'
export const DELETE_PROJECT_PHOTO_FAILURE = 'DELETE_PROJECT_PHOTO_FAILURE'

export const UPDATE_PROJECT_PDF = 'UPDATE_PROJECT_PDF'
export const UPDATE_PROJECT_PDF_SUCCESS = 'UPDATE_PROJECT_PDF_SUCCESS'
export const UPDATE_PROJECT_PDF_FAILURE = 'UPDATE_PROJECT_PDF_FAILURE'

export const GENERATE_PROJECT_REPORT = 'GENERATE_PROJECT_REPORT'
export const GENERATE_PROJECT_REPORT_SUCCESS = 'GENERATE_PROJECT_REPORT_SUCCESS'
export const GENERATE_PROJECT_REPORT_FAILURE = 'GENERATE_PROJECT_REPORT_FAILURE'

export const FETCH_BUILDINGS = 'FETCH_BUILDINGS'
export const FETCH_BUILDINGS_SUCCESS = 'FETCH_BUILDINGS_SUCCESS'
export const FETCH_BUILDINGS_FAILURE = 'FETCH_BUILDINGS_FAILURE'

export const FETCH_BUILDING = 'FETCH_BUILDING'
export const FETCH_BUILDING_SUCCESS = 'FETCH_BUILDING_SUCCESS'
export const FETCH_BUILDING_FAILURE = 'FETCH_BUILDING_FAILURE'

export const CREATE_BUILDING = 'CREATE_BUILDING'
export const CREATE_BUILDING_SUCCESS = 'CREATE_BUILDING_SUCCESS'
export const CREATE_BUILDING_FAILURE = 'CREATE_BUILDING_FAILURE'

export const UPDATE_BUILDING = 'UPDATE_BUILDING'
export const UPDATE_BUILDING_SUCCESS = 'UPDATE_BUILDING_SUCCESS'
export const UPDATE_BUILDING_FAILURE = 'UPDATE_BUILDING_FAILURE'

export const DELETE_BUILDING = 'DELETE_BUILDING'
export const DELETE_BUILDING_SUCCESS = 'DELETE_BUILDING_SUCCESS'
export const DELETE_BUILDING_FAILURE = 'DELETE_BUILDING_FAILURE'